pipeline {
    agent any
    stages {
        stage('Build') {
            
            steps {
                sh 'echo "noob"'
            }
        }
        stage('Test') {
           
            steps {
                  sh 'echo "noob"'
            }
            
        }
        stage('Deliver') {
           
            steps {
                 sh 'echo "noob"'
            }
           
        }
    }
}
