pipeline {
    agent any
    stages {
        stage('Build') {
            
            steps {
                sh 'echo "noob"'
            }
        }
        stage('Deliver') {
           
            steps {
                 sh 'echo "noob"'
            }  
        }
        stage('OWASP DependencyCheck') {
            steps {
             dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'OWASP Dependency-Check'   
            }
        }
        
        stage('Test') {
               steps {
                sh 'phpunit --log-junit logs/unitreport.xml -c tests/phpunit.xml tests'
               }
           }
    }
    post {
        success {
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        }
    }
    post {
           always{
               junit testResults: 'logs/unitreport.xml'
           }
       }

}
