pipeline {
    agent any
    stages {
        stage('Build') {
            
            steps {
                sh 'echo "noob"'
            }
        }
        stage('Test') {
           
            steps {
                  sh 'echo "noob"'
            }
            
        }
        stage('Deliver') {
           
            steps {
                 sh 'echo "noob"'
            }
           
        }
        
        stage('OWASP DependencyCheck') {
            steps {
             dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'OWASP Dependency-Check'   
            }
        }
    }
    
    post {
        success {
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        }
    }
}
